version: "3.9"
services:
  db:
    container_name: db
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: note_app
      MYSQL_USER: user
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
  app:
    container_name: app
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/go/Dockerfile
      target: dev
    environment:
      ENV: DEV
      PORT: 8080
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
volumes:
  db_data:
