// Code generated by ogen, DO NOT EDIT.
package api

type CreateNoteRes interface {
	createNoteRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteNoteRes interface {
	deleteNoteRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetNoteRes interface {
	getNoteRes()
}

type GetNotesRes interface {
	getNotesRes()
}

type GetUserRes interface {
	getUserRes()
}

type GetUsersRes interface {
	getUsersRes()
}

type UpdateNoteRes interface {
	updateNoteRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
